version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: user_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}   # Ensure user matches .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: ${POSTGRES_DB:-user_db}  # Ensure database name matches .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-test}", "-d", "${POSTGRES_DB:-user_db}"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: user_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      APP_ENV: dev
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: user_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8080:8080"
    command: ["/root/user-api"]  # Run the compiled binary instead of "go run main.go"

  test:
    profiles: ["test"]
    build:
      context: .
      dockerfile: Dockerfile_test
    container_name: test_runner
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: test_db
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: "5432"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - .:/app
volumes:
  postgres_data:
